### PR TITLE
Update to use mwdebug1001/2

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Comment by hashar** [comment]
Guess that will serves @paladox  :]

**Comment by paladox** [comment]
Thankyou

**Comment by paladox** [comment]
@addshore @hashar this should also be done on the chrome one too please?

https://github.com/wikimedia/ChromeWikimediaDebug/blob/master/popup.html#L12

**Comment by hashar** [comment]
Yeah it is covered:


https://github.com/wikimedia/ChromeWikimediaDebug/pull/6
https://github.com/wikimedia/FirefoxWikimediaDebug/pull/19
https://github.com/paladox/EdgeWikimediaDebug/pull/1

**Comment by paladox** [comment]
Thanks.

**Pull request merged**
